language: node_js
node_js:
    - "node"

notifications:
    email: false

branches:
    only:
        - master
cache:
    directories:
        - node_modules

script:
    - npm run build

deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_ACCESS_SECRET
      bucket: "leone-apiary"
      skip_cleanup: true
      local_dir: dist

