language: node_js
node_js:
    - "node"
notifications:
    email: false
branches:
    only:
        - master
git:
    depth: false
cache:
    directories:
        - node_modules
script:
    - npm run build
deploy:
    - provider: s3
      access_key_id: $ACCESS_KEY_ID
      secret_access_key: $SECRET_ACCESS_KEY
      bucket: "apiary.marioleone.me"
      skip_cleanup: true
      local_dir: dist

